
#controllers:
#    resource: ../src/Controller/
#    type: annotation

#kernel:
#    resource: ../src/Kernel.php
#    type: annotation

home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /logements
  controller: App\Controller\PropertyController::index

property.show:
    path: /logements/{slug}-{id}
    controller: App\Controller\PropertyController::show
    requirements:
        slug: '[a-zA-Z0-9-_\/-]+'
